apiVersion: v1
kind: Service
metadata:
  name: vprodb # the name of the mysql host in the application.properties file
spec:
  type: ClusterIP
  selector:
    app: vprodb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: app-db-port