apiVersion: v1
kind: Service
metadata:
  name: vprocache01 # the name of the mysql host in the application.properties file
spec:
  type: ClusterIP
  selector:
    app: app-mc
  ports:
    - protocol: TCP
      port: 11211
      targetPort: app-mc-port