apiVersion: v1
kind: Service
metadata:
  name: vpromq01 # the name of the mysql host in the application.properties file
spec:
  type: ClusterIP
  selector:
    app: rmq-mc
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672